[package]
name = "rpn-wasm"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
rpn-core = { path = "../rpn-core" }
rpn-std = { path = "../rpn-std" }
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = ["console"] }
